apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa
  finalizers: []
spec:
  destination:
    name: ''
    namespace: qa
    server: 'https://kubernetes.default.svc'
  source:
    path: ./environment-promotion/envs/qa
    repoURL: 'https://github.com/todaywasawesome/gitops-cert-level-2-examples/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true